# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               IDEEAS Lab Title
tagline:             'IDEEAS Lab Site tag'
description:         'IDEEAS desc'
url:                 http://ideeaslab.github.io
baseurl:             ''
# The following line is required for Jekyll >=3 support
gems:                [jekyll-paginate, jekyll-gist]
paginate:            5

# About/contact
author:
  name:              AK
  url:               http://ideeaslab.github.io
  email:             thomas.girke@ucr.edu

# Custom vars
version:             Lanyon
